[project]
name = "sdlc-app-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph>=0.6.6",
    "notebook>=7.4.5",
    "python-dotenv>=1.1.1",
]
